name: sa_somativo
description: "App de registro de ponto com geolocalização e biometria"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  local_auth: ^2.1.7
  flutter_dotenv: ^5.1.0 # opcional, para variáveis de ambiente

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
